name:                Hastructure
version:             0.1.0.0
github:              "githubuser/Hastructure"
license:             BSD3
author:              "Xiaoyu"
maintainer:          "example@example.com"
copyright:           "2022 Xiaoyu, Zhang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Hastructure#readme>

dependencies:
- base
- time
- lens
- Spock
- aeson
- text
- bytestring
- template-haskell
- json-schema

library:
  source-dirs: src

executables:
  Hastructure-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hastructure
    - time
    - lens
    - Spock
    - aeson
    - text
    - containers
    - unordered-containers
      #- timeseries

tests:
  Hastructure-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hastructure
